version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    ports:
      - '5444:5432'
    container_name: postgresdb
    hostname: postgresdb
    volumes:
      - postgres-keycloak-volnew1:/var/lib/postgresql/data

volumes:
   postgres-keycloak-volnew1:
