version: '3.3'

services:
  db:
    image: postgresjenkins
    restart: always
    ports:
      - '5444:5432'
    container_name: postgresdb
    hostname: postgresdb
    volumes:
      - postgres-keycloak-volnew1:/var/lib/postgresql/data

volumes:
   postgres-keycloak-volnew1:
